### ISSUE TITLE
Homework areas for improvement

### ISSUE THREAD

**Issue by hynesy23** [ttudorandrei/readme_generator#1]
https://github.com/ttudorandrei/readme_generator/blob/67bbf14199b40b42d7e2bf14a8eead7ffebeac54/index.js#L5
Try and keep your internal and external imports separated by a line

https://github.com/ttudorandrei/readme_generator/blob/67bbf14199b40b42d7e2bf14a8eead7ffebeac54/utils/generateMarkdown.js#L24
This should be const (same with line 35)

https://github.com/ttudorandrei/readme_generator/blob/67bbf14199b40b42d7e2bf14a8eead7ffebeac54/utils/generateMarkdown.js#L27
You can just return an empty string here. Same with line 29, no need to assign a variable while your return it, just return what you want the variable value to be (same for tableOfContentsScreenshotSection  function)

https://github.com/ttudorandrei/readme_generator/blob/67bbf14199b40b42d7e2bf14a8eead7ffebeac54/utils/generateMarkdown.js#L23
Try and keep names like this for variables containing a boolean value.

**Comment by ttudorandrei** [comment]
I`ve corrected the issues you have highlighted!
